FROM public.ecr.aws/docker/library/python:3.11.9-slim-bullseye
COPY . /app
WORKDIR /app

RUN apt-get update
RUN apt-get install libgomp1
RUN apt-get -y install git

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt 

CMD ["python", "-m","src"]
EXPOSE 80